### PR TITLE
Htmlcss brnh

### PR DESCRIPTION
**Pull request by lizzy-km**
**Hello World Repository Setup**

In this project, I will be setting up a "Hello world" repository. While this project may not involve complex coding, it is an essential exercise to master all the tools and best practices I have learned about in previous steps. These skills are crucial for all Microverse projects and will most likely be valuable in my future job as well. Additionally, this project marks my first step towards receiving a code review, a process that will be a part of all Microverse projects.

**Introduction Video**

Before getting started, I watched the introduction video to gain a clear understanding of the project's objectives and expectations.

**General Requirements**

Before finalizing my project, I made sure to double-check the following requirements:

**Linter Errors**
I ensured that there are no linter errors in my code. This demonstrates my commitment to writing clean and error-free code.

**GitHub Flow**
I followed the GitHub flow while working on this project. This includes creating branches, making commits, and creating pull requests to facilitate collaboration and code review.

**Documentation**
I documented my work thoroughly. This documentation serves as a record of my project's setup and can help others understand and contribute to the project in the future.

**Conclusion**

Setting up this "Hello world" repository may seem simple, but it is a foundational step in my journey as a developer. It reinforces the importance of proper coding practices, collaboration through version control, and documentation, all of which are vital skills for success in Microverse and my future career.

### CODE REVIEW

**Review by HtetWaiYan7191 — CHANGES_REQUESTED** [review]
Hi @lizzy-km , 



Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Correct Git Flow :heavy_check_mark: 
Descriptive Pr :heavy_check_mark: 

## Required Changes ♻️

Please kindly follow the instructions from the below image 😁 

Screenshot (163)


There are two titles currently please kindly consider to remove one 💯 

Screenshot (164)

Please consider to remove completed from the README instead of adding line-through style in the list . 
Screenshot (165)

Kindly consider to remove the comments description lines since the purpose of these comments are only show some sample sentences for you .  😁 

Screenshot (166)

You can remove the FAQ section from the README file  since we are not using it . 😁 
Screenshot (167)

## Optional suggestions



_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the 

approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by lizzy-km** [comment]
Update README.md

**Comment by lizzy-km** [comment]
Final changes for README.md

**Review by HtetWaiYan7191 — APPROVED** [review]
Hi @lizzy-km  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉


## Highlights
- Well Structed PR ✔️
- Linters pass ✔️
- Correct Git Flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
